name: schulupparent
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.16
  # cached_network_image: ^3.4.1
  get: ^4.6.6
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2  
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  fl_chart: ^1.1.1
  overlay_kit: ^1.1.2
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_html: ^3.0.0
  pull_to_refresh_flutter3: ^2.0.2
  url_launcher: ^6.3.2
  alert_info: ^0.0.6
  # signalr_netcore: ^1.4.4
  
  logger: ^2.6.2
  # signalr_core: ^1.1.2
  cached_network_image: ^3.4.0
  signalr_netcore3: ^1.3.8
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  sqflite: ^2.4.2
  path: ^1.9.1
  responsive_grid_list: ^1.4.1
  # signalr_client: ^1.0.0
  nfc_manager:
  nfc_manager_ndef:
  scanning_effect:
  sqflite_common_ffi: ^2.4.0+1
  get_storage: ^2.1.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Rubik
      fonts: 
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
          weight: 200
    - family: Inter Tight
      fonts: 
        - asset: assets/fonts/InterTight-SemiBold.ttf
          weight: 600
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700      
 

launcher_name:
  default: "Schulup"




flutter_launcher_icons:
  image_path: "assets/images/1024.png"
  android:
    generate: true
    image_path: "assets/images/1024.png"
    background_color: "#004694"
    theme_color: "#004694"
  linux:
    generate: true
    image_path: "assets/images/1024.png"
    background_color: "#004694"
    theme_color: "#004694"
  ios:
    generate: true
    image_path: "assets/images/1024.png"
    background_color: "#004694"
    theme_color: "#004694"
    remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/1024.png"
    background_color: "#004694"
    theme_color: "#004694"
  windows:
    generate: true
    image_path: "assets/images/1024.png"
    background_color: "#004694"
    theme_color: "#004694"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/1024.png"
    background_color: "#004694"
    theme_color: "#004694"